# docker-compose.yml

version: '3'

services:
  app1_todo-list:
    build: app01_todo-list/
    image: python-course-app01
    container_name: 01-todo-list
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./app01_todo-list/src/todos.txt:/app/todos.txt

  app2_portfolio:
    build: app02_portfolio/
    image: python-course-app02
    container_name: 02-portfolio
    restart: unless-stopped
    ports:
      - "8502:8501"

  app7-weather-forecast-data:
    build: app07_weather-forecast-data/
    image: python-course-app07
    container_name: 07-weather
    restart: unless-stopped
    ports:
      - "8503:8501"
  
  app16-flask-form:
    build: app16_flask-form/
    image: python-course-app16
    container_name: 16-flask-form
    restart: unless-stopped
    ports:
      - "5001:5001"

  app17-django-form:
    build: app17_django-form/
    image: python-course-app17
    container_name: 17-django-form
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app17_django-form:/app

  app18-restaurant-menu:
    build: app18_restaurant-menu/
    image: python-course-app18
    container_name: 18-restaurant-menu
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./app18_restaurant-menu:/app
